[tool.poetry]
name = "elevators-prod"
version = "0.1.0"
description = ""
authors = ["saichenko <vladislav.saichenko@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
